name: Listing S3 Buckets

on:
    push:
        branches:
            - master
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    listing_buckets:
        runs-on: ubuntu-latest
        steps:
            - name: Setup AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.IAM_ROLE }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: List S3 Buckets
              env:
                  AWS_REGION: ${{ secrets.AWS_REGION }}
              run: |
                  echo "Listing S3 Buckets"
                  aws s3 ls
