name: Test

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    log_message:
        runs-on: ubuntu-latest
        steps:
            - name: Log
              run: echo "The Workflow is working!"
